addSbtPlugin("com.github.sbt"     %% "sbt-native-packager" % "1.9.4")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"         % "1.22.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.5.0")
addSbtPlugin("com.w47s0n"          % "sbt-scalajs-cli"     % "0.1.1")
